brew "asdf"
brew "awscli"
brew "bitwarden-cli"
brew "ca-certificates"
brew "chezmoi"
brew "cmake" # for vterm
brew "coreutils"
brew "dnsmasq"
brew "docker-compose"
brew "findutils"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gpg"
brew "graphviz"
brew "grpcurl"
brew "helix"
brew "kubie"
brew "libpq", link: true
brew "libtool" # for vterm
brew "libvterm" # for vterm
brew "ripgrep"
brew "tenv"
brew "typescript-language-server"

cask "alacritty"
cask "claude"
cask "claude-code"
cask "docker-desktop"
cask "emacs"
cask "google-chrome"
cask "notunes"
cask "slack"
cask "visual-studio-code"
