tap "homebrew/cask-fonts"

brew "chezmoi"
brew "ca-certificates"
brew "dnsmasq"
brew "gh"
brew "git"
brew "libpq", link: true
brew "eslint"
brew "ripgrep"
brew "coreutils"
brew "gnu-sed"
brew "findutils"
brew "age"

cask "docker"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "emacs"
cask "font-gnu-unifont"
cask "font-fantasque-sans-mono-noloopk"
