tap "homebrew/cask-fonts"

brew "chezmoi"
brew "ca-certificates"
brew "dnsmasq"
brew "gh"
brew "git"
brew "libpq", link: true
brew "eslint"
brew "ripgrep"
brew "coreutils"
brew "gnu-sed"
brew "findutils"
brew "gpg"
brew "awscli"
brew "age"
brew "graphviz"
brew "typescript-language-server"

cask "docker"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "emacs"
