#+TITLE: Dotfiles
#+AUTHOR: Xavier Capaldi
#+PROPERTY: header-args :results silent

My dotfiles using [[https://www.chezmoi.io/][Chezmoi]]:

- [[file:dot_zshrc][zshrc]]
- [[file:dot_psqlrc][psqlrc]]
- [[file:dot_config/emacs/config.org][emacs]]

Note that this is currently used to configure my personal openSUSE Tumbleweed box and my work MacOS box.
In both cases I've slowly steered away from super complex configurations in favor of using default functionality.
I would prefer to spend time potentially lost in a rabbit hole of configuration on real projects.

* Personal linux box
I prefer to use [[https://www.opensuse.org/#Tumbleweed][openSUSE Tumbleweed Linux]] as it is a well-behaved modern Linux distribution that is dedicated to open-source.
I previously used Fedora linux but I grew tired of the quick release schedule.
Now that I am working, I no longer spend my entire day on my personal machine so I am favoring a stable rolling-release distribution that requires less-frequent upkeep. 

** Installing a minimal system
I cut my teeth on minimal Linux systems running tiling window managers like [[https://dwm.suckless.org/][DWM]] and [[https://www.nongnu.org/ratpoison/][Ratpoison]].
While I still appreciate the minimalism, I've decided to try and focus more on building things rather than configuring my system to be more efficient.
I am inspired by xkcd's [[https://xkcd.com/1205/][Is It Worth The Time?]].
Conveniently if you install [[https://get.opensuse.org/tumbleweed/][openSUSE tumbleweed]] you can install a minimal graphical system.
This actually installs [[https://ice-wm.org/][IceWM]] which is a fairly minimal floating window manager with a Windows-ish UX.
It's ugly but works well with next to no configuration.
I'm seeing how efficient my workflow is with this kind of setup.
As a plus, a non-tech person could probably navigate this setup without guidance.
 
*** Wifi
#+BEGIN_SRC sh
sudo zypper install NetworkManager-applet
#+END_SRC

*** Audio
#+BEGIN_SRC sh
sudo zypper install alsa-firmware pulseaudio pavucontrol pasystray
#+END_SRC

*** Manage display
#+BEGIN_SRC sh
sudo zypper install arandr xbacklight
#+END_SRC

*** Mount and manage external drives
#+BEGIN_SRC sh
sudo zypper install udisks2 udiskie
#+END_SRC

*** [[https://github.com/openSUSE/opi][OBS Package Installer]]
This enables installing things outside the main open-source package repository.
We need it specifically to install media codecs.

#+BEGIN_SRC sh
sudo zypper install opi
opi codecs
#+END_SRC 

*** Chezmoi
Of course we need to install and initialize [[https://www.chezmoi.io/][Chezmoi]]:

#+BEGIN_SRC sh
sudo zypper install chezmoi
chezmoi init xcapaldi
chezmoi apply
#+END_SRC

*** Use posix-compliant shell
Alias =sh= to =dash= instead of =bash=.
This should speed up posix-compliant scripts.

#+BEGIN_SRC sh
sudo zypper install dash
sudo rm /bin/sh
sudo ln -s /bin/dash /bin/sh
#+END_SRC

*** Replace screenlocker
#+BEGIN_SRC sh
sudo zypper install xlockmore -xscreensaver -xscreensaver-data -xscreensaver-lang
#+END_SRC
